using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SearchService;
using UnityEngine.UI;

public class GameManager : MonoBehaviour
{
    //ì‹±ê¸€í†¤ ê´€ë ¨ ë³€ìˆ˜
    public static GameManager I;

    //ì‹œê°„ ê´€ë ¨ ë³€ìˆ˜
    public GameObject card;
    public GameObject TimeCanvas;
    public Text timetxt;
    float time = 60.0f;

    //ì¹´ë“œ ë°°ì¹˜
    public bool sortCompleted = false;
    public CardDealer cardDealer;

    //ê²Œì„ ì¢…ë£Œ ê´€ë ¨ ë³€ìˆ˜
    public GameObject endcanvas;

    //Match ê´€ë ¨ ë³€ìˆ˜
    public GameObject firstCard;
    public GameObject secondCard;

    //ê²°ê³¼ ì°½ ì ìˆ˜ ê´€ë ¨ ë³€ìˆ˜
    public Text counttxt;
    public Text trytxt;
    int matchCount;
    int matchTry;
    int matchFailed;
    int totalScore;
    int bestScore = 0;

    //MatchUI ê´€ë ¨ ë³€ìˆ˜
    public GameObject matchCanvas;
    public GameObject unMatchCanvas;
    public string ownerName;
    //public Text ownerNameTxt;


    //ì¹´ë“œ ì´ˆê¸°í™” ê´€ë ¨ íƒ€ì´ë¨¸
    float PickTime = 0f;

    void Awake()
    {
        I = this;
    }

    // Start is called before the first frame update
    void Start()
    {
        LoadBestScore();
        SpawnUI();

        Time.timeScale = 1.0f;
        Debug.Log(PlayerPrefs.GetInt("ClearStage"));
    }

    // Update is called once per frame
    void Update()
    {
        Timer();

        int childLeft = GameObject.Find("Cards").transform.childCount;
        if (childLeft == 0)
        {
            //44ë³´ë“œ í´ë¦¬ì–´ ì—¬ë¶€ë¥¼ ì €ì¥í•˜ê¸° ìœ„í•œ ì½”ë“œ
            PlayerPrefs.SetInt("ClearStage", 1);
            Invoke("EndGame", 1.1f);
        }

        unPickCard();
    }
    public void OnTimer()
    {
        TimeCanvas.SetActive(true);
        sortCompleted = true;
    }

    //Timer..
    void Timer()
    {   

        if (sortCompleted == true)  // true ì¼ë•Œ Timerê°€ ì‹¤í–‰ ë¨..
        {
            time -= Time.deltaTime;
            timetxt.text = time.ToString("N1");

            if (time <= 0.00f)
            {
                Time.timeScale = 0.0f;
                EndGame();
                BGM.instance.SpeedUp(0);
                timetxt.text = "<color=black>" + time.ToString("N1") + "</color>";
            }
            else if (time < 10.00f)
            {
                BGM.instance.SpeedUp(2);
                timetxt.text = "<color=red>" + time.ToString("N1") + "</color>";
            }
            else if (time < 30.00f)
            {
                BGM.instance.SpeedUp(1);
                timetxt.text = "<color=orange>" + time.ToString("N1") + "</color>";
            }
            else
            {
                timetxt.text = "<color=white>" + time.ToString("N1") + "</color>";
            }
        }
    }


    //ë§¤ì¹˜ ì‹œë„ í•¨ìˆ˜
    public void IsMatched()
    {
        
        string firstCardImage = firstCard.transform.Find("Front").GetComponent<SpriteRenderer>().sprite.name;
        string secondCardImage = secondCard.transform.Find("Front").GetComponent<SpriteRenderer>().sprite.name;
        matchTry++;

        if (firstCardImage == secondCardImage)
        {

            //audioManager ì—ì„œ ë°›ì•„ì™€ì„œ true ì½”ë“œ ì‹¤í–‰
            audioManager.instance.matchPlay();
            

            firstCard.GetComponent<Card>().DestroyCard();
            secondCard.GetComponent<Card>().DestroyCard();
            //Debug.Log(firstCard.GetComponent<Card>().Owner);
            //ownerNameTxt.text = firstCard.GetComponent<Card>().Owner;

            ownerName = GameManager.I.firstCard.GetComponent<Card>().Owner;

<<<<<<< Updated upstream
            //ë§¤ì¹­ ì„±ê³µ UIê°€ ë‚˜íƒ€ë‚¬ë‹¤ê°€ ì‚¬ë¼ì§
            matchCanvas.SetActive(true);
            Invoke("HideMatchUI", 1.0f);
=======
            //¸ÅÄª ¼º°ø UI°¡ ³ªÅ¸³µ´Ù°¡ »ç¶óÁü
            Instantiate(matchCanvas);
            
>>>>>>> Stashed changes

            //ë§¤ì¹˜ ì„±ê³µ ì¹´ë“œ ì¹´ìš´í„°
            matchCount++;

        }
        else
        {
<<<<<<< Updated upstream
            Debug.Log("UnMatched!");
            //audioManager ì—ì„œ ë°›ì•„ì™€ì„œ false ì½”ë“œ ì‹¤í–‰
=======
            //audioManager ¿¡¼­ ¹Ş¾Æ¿Í¼­ false ÄÚµå ½ÇÇà
>>>>>>> Stashed changes
            audioManager.instance.unmatchPlay();


            firstCard.GetComponent<Card>().CloseCard();
            secondCard.GetComponent<Card>().CloseCard();

<<<<<<< Updated upstream
            //ë§¤ì¹­ ì‹¤íŒ¨ UIê°€ ë‚˜íƒ€ë‚¬ë‹¤ê°€ ì‚¬ë¼ì§
            unMatchCanvas.SetActive(true);
            Invoke("HideUnMatchUI", 1.0f);
=======
            //¸ÅÄª ½ÇÆĞ UI°¡ ³ªÅ¸³µ´Ù°¡ »ç¶óÁü
            Instantiate(unMatchCanvas);
>>>>>>> Stashed changes

            //ì‹œê°„ 2ì´ˆ ê°ì†Œ..
            matchFailed++;
            time -= 1;
        }
        firstCard = null;
        secondCard = null;
    }

<<<<<<< Updated upstream
    //ë§¤ì¹­ê²°ê³¼ UI Hide
    public void HideMatchUI()
    {
        matchCanvas.gameObject.SetActive(false);
    }
    public void HideUnMatchUI()
    {
        unMatchCanvas.SetActive(false);
    }

    //ë§¤ì¹­ ì„±ê³µ ì‹œ UI ë…¸ì¶œ
=======
    //¸ÅÄª ¼º°ø ½Ã UI ³ëÃâ
>>>>>>> Stashed changes
    void EndGame()
    {
        //ì ìˆ˜ = ë‚¨ì€ ì‹œê°„("N0") * 10 + ë§¤ì¹­ ì„±ê³µ(íšŸìˆ˜ * 50) - ë§¤ì¹­ ì‹¤íŒ¨(íšŸìˆ˜ * 15)
        totalScore = ((int)time * 10) + (matchCount * 50) - (matchFailed * 15);
        
        timetxt.text = $"ë‚¨ì€ ì‹œê°„ : {time.ToString("N1")}";
        trytxt.text = $"ì‹œë„ íšŸìˆ˜ : {matchTry}";
        /*counttxt.text = $"ì ìˆ˜ : {matchCount}";*/
        counttxt.text = "ì ìˆ˜ : " + totalScore.ToString();

        if(bestScore < totalScore)
        {
            SaveBestScore(totalScore);
        }

        Time.timeScale = 0f;
        endcanvas.SetActive(true);
        TimeCanvas.SetActive(false);
        BGM.instance.SpeedUp(0);
    }


    void SpawnUI()
    {
        Instantiate(Resources.Load<GameObject>("UI/BestScore"));
    }

    void LoadBestScore()
    {
        switch(cardDealer.stage)
        {
            case CardDealer.EStage.Card16EA:
                if (PlayerPrefs.HasKey("4by4BestScore"))
                {
                    bestScore = PlayerPrefs.GetInt("4by4BestScore");
                }
                break;

            case CardDealer.EStage.Card36EA:
                if (PlayerPrefs.HasKey("6by6BestScore"))
                {
                    bestScore = PlayerPrefs.GetInt("6by6BestScore");
                }
                break;
        }
    }

    void SaveBestScore(int bestScore)
    {
        switch (cardDealer.stage)
        {
            case CardDealer.EStage.Card16EA:
                PlayerPrefs.SetInt("4by4BestScore", totalScore);
                break;

            case CardDealer.EStage.Card36EA:
                PlayerPrefs.SetInt("6by6BestScore", totalScore);
                break;
        }
    }

    public int GetBestScore()
    {
        return bestScore;
    }
    
    //3ì´ˆ ì´ìƒ secondCardë¥¼ ë’¤ì§‘ì§€ ì•Šìœ¼ë©´ firstCardë¥¼ ì´ˆê¸°í™” í•©ë‹ˆë‹¤.
    void unPickCard()
    {
        if(firstCard != null &&  secondCard == null)
        {
            PickTime += Time.deltaTime;
        }
        else
        {
            PickTime = 0f;
        }
        if(PickTime > 3.0f)
        {
            firstCard.GetComponent<Card>().CloseCard();
            firstCard = null;
            PickTime = 0f;
        }
    }
}
